# Generated by Django 4.2.6 on 2024-01-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_name',
            new_name='name',
        ),
    ]
